---
title: "Grafico"
author: "Salvador Gisbert Sempere"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Primero importamos los datos
```{r}

library(readr)
owid_covid_data <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

```


##Empezamos a recopilar las variables que a침adiremos al grafico. Los paises que se muestran en la imagen de referencia
```{r}

Japon <- owid_covid_data[owid_covid_data$location == "Japan", ]
Canada <- owid_covid_data[owid_covid_data$location == "Canada", ]
Alemania <- owid_covid_data[owid_covid_data$location == "Germany", ]
Francia <- owid_covid_data[owid_covid_data$location == "France", ]
EstadosUnidos <- owid_covid_data[owid_covid_data$location == "United States", ]
Italia <- owid_covid_data[owid_covid_data$location == "Italy", ]
ReinoUnido <- owid_covid_data[owid_covid_data$location == "United Kingdom", ]
Espana <- owid_covid_data[owid_covid_data$location == "Spain", ]

```



##Ponemos en marcha el gr치fico

Recogemos todas las variables en una para agilizar la construcci칩n del gr치fico
```{r}
library(ggplot2)
paises <- owid_covid_data[owid_covid_data$location == 'United States' | owid_covid_data$location == 'Italy' | owid_covid_data$location == 'France' | owid_covid_data$location == 'Germany' | owid_covid_data$location == 'Canada' | owid_covid_data$location == 'Japan' | owid_covid_data$location == 'United Kingdom' | owid_covid_data$location == 'Spain', ]

grafico <- ggplot(paises, aes(x = date, y = new_deaths_smoothed_per_million, colour = location)) + geom_line()
grafico
```

